// const catchErr = async (cb: () => void) => {
//     try {
//         await cb()
//     } catch (error) {
//         throw new Error
//     }
// }

// export default catchErr
